### ISSUE TITLE
Insufficient checks for PEM file existence 

### ISSUE THREAD

**Issue by HARVS1789UK** [getyoti/yoti-php-sdk#61]
Seen in a recent (2019-04-30) composer installation of getyoti/yoti-php-sdk at version `2.2.0` 

`Yoti\YotiClient::extraxctPemContent()` takes a file path, checks the file exists and validates that the file contains a valid private key.

The following lines are responsible for checking the file exists and if so updating the `$pem` variable* to contain the private key data.

```
        // Check that file exists if user passed PEM as a local file path
        if (strpos($pem, 'file://') !== false && !file_exists($pem)) {
            throw new YotiClientException('PEM file was not found.', 400);
        }

        // If file exists grab the content
        if (file_exists($pem)) {
            $pem = file_get_contents($pem);
        } 
``` 

I have a few questions and issues here:

- 1 - With regards to the comment with reference to 'local file path', I appreciate that (to quote from it's docs) file_exists() can:

>As of PHP 5.0.0, this function can also be used with some URL wrappers.

but in the context of a downloaded .pem file to be stored in your applications code base, is anything **but** a local path likely to be used?

- 2 - I don't know if this is a Windows thing (I don't think so?) but there is no need to prefix a local file path with 'file://' to my knowledge and the presence of that additional check means any local file path in the form of, for example `/troublesome/absolute/path/to/my/file.pem` will fail to throw the "PEM file was not found" exception and instead will throw "PEM key content is invalid" once the file path is passed to `openssl_get_privatekey()` (as that will still be what `$pem` contains, another good reason not to use the same, passed by reference variable to hold the file path and file contents).
This is pretty misleading and leads to unnecessary additional debugging when you accidentally specify the wrong local file path

- 3 - What is the purpose of the second call to `file_exists()` on line 350?
If the issues in No. 2 above were remedied it would be unnecessary but if it is required, surely it too should have an `else {}` condition which throws the same "PEM file was not found" exception?

Certainly I feel that the `file_exists()` logic here needs some changes to prevent misleading error messaging, and potentially the entire method could be modified to be a little clearer, perhaps as per my suggestion below:

```
    /**
     * Validate and store PEM file content.
     *
     * @param string $pem - An absolute path to the PEM file containing the Yoti
     * applications private key
     * @throws YotiClientException
     * @return void
     */
    private function extractPemContent($pemPath)
    {
        // Check PEM path is provided
        if (!$pemPath) {
            throw new YotiClientException('PEM file path is required', 400);
        }

        // Check that the file exists
        if (!file_exists($pemPath)) {
            throw new YotiClientException('PEM file was not found.', 400);
        }

        // Grab the content
        $pemData = file_get_contents($pem);

        // Check if key is valid
        if (!openssl_get_privatekey($pemData)) {
            throw new YotiClientException('PEM key content is invalid', 400);
        }

        $this->pemContent = $pemData;
        
        return;
    }
```

I would be happy to raise a new pull request to address either of these suggestions if you can comment on their suitability and also confirm which branch to submit the PR against please?

*Note: It seems an odd design choice to pass `$pem` by reference and update it's value from a file path to the file data within this method, then have `$this->pemContent = $pem;` a few lines after in the constructor? Why not just have that line as the last line of `extraxctPemContent()` and not pass it's sole param by reference?

**Comment by davidgrayston** [comment]
Hi Joe,

We appreciate this feedback and agree that we can make this much easier to follow.

1. `$pem` can in fact be either a path to PEM file _or_ the PEM file contents as a string, which allows for flexibility if the file contents are not in a local file.
&nbsp;
This has however highlighted that we should really be using `is_file()`, as `file_exists()` also checks whether a directory exists.
&nbsp;
I also appreciate it's not very clear having an argument for both file path and PEM string, and perhaps we will consider abstracting this in the next major version to allow users to build a PEM object using builder methods rather than multi purpose constructor arguments.
&nbsp;
To address this in the current minor version, we'll add better PHPDoc descriptions and use `is_file()`

2. `file://` is a valid [PHP stream wrapper](https://www.php.net/manual/en/wrappers.php), so we need to allow for this. We throw the exception when `file://` is used explicitly and the file doesn't exist, as we know in this case that we are looking for a local file path.
&nbsp;
If the file does not exist we assume it is a PEM string and validate using `openssl_get_privatekey()`.
&nbsp;
I agree we can make the exception message clearer to prevent the need to look into the SDK code.

3. We only fetch the file contents when the file exists as we also allow the PEM contents to be passed as a string.

4. I agree, we can move `$this->pemContent = $pem` into `extractPemContent()`

Thank you for taking the time to open this issue and giving such a detailed and helpful summary!

I'll open a PR to address these issues and can add you as a reviewer

**Comment by HARVS1789UK** [comment]
Hi @davidgrayston,

Thanks for coming back to me, I have checked out your PR and would agree that it all looks like sensible changes.

To clarify, I was not suggesting the `file://` shouldn't be supported, just that `/` should (without inaccurate exception messages being thrown back).

I see you have remedied this by updating the last exception message to "PEM file path or content is invalid".

Always happy to help, I will keep an eye out for when this is merged and released.

**Comment by davidgrayston** [comment]
Thank you @HARVS1789UK - we will look at improving the way PEM files are used in the next major release
